// /*
// Auto-generated by: https://github.com/pmndrs/gltfjsx
// Author: MozillaHubs (https://sketchfab.com/mozillareality)
// License: CC-BY-NC-SA-4.0 (http://creativecommons.org/licenses/by-nc-sa/4.0/)
// Source: https://sketchfab.com/3d-models/sky-pano-milkyway-0016725c047a4ea18cd0b5e5ef2fe441
// Title: Sky Pano - Milkyway
// */

// import { useRef,useEffect } from "react";
// import { useGLTF } from "@react-three/drei";
// import { useFrame,useThree } from "@react-three/fiber";
// import {a} from '@react-spring/three'
// import Sky_panoScene from '../assets/3d/sky_pano_-_milkyway.glb'

// const Sky_pano = (props) => {
//   const Sky_panoRef = useRef();
//   const { nodes, materials } = useGLTF(Sky_panoScene);
//   return (
//     <a.group  ref={Sky_panoRef} {...props} >
//       <group rotation={[-Math.PI / 2, 0, 0]} scale={0.01}>
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.PanoSphere_lambert1_0.geometry}
//           material={materials.lambert1}
//           rotation={[Math.PI / 2, 0, 0]}
//         />
//       </group>
//     </a.group>
//   );
// }

// useGLTF.preload("/sky_pano_-_milkyway.glb");

// export default Sky_pano;


import { useAnimations,useGLTF } from '@react-three/drei'
import {useRef,useEffect} from 'react'
import {useFrame} from '@react-three/fiber'

import Sky_panoScene from '../assets/3d/sky_pano_-_milkyway.glb'

const Sky_pano = ({isRotating, ...props}) => {
  const ref =  useRef();
  const {scene,animations} =useGLTF(Sky_panoScene);

  useFrame((_,delta) =>{
    if(isRotating){
      ref.current.rotation.y +=0.15 * delta
    }
    else{
      ref.current.rotation.y +=0.02 * delta
    }
  })
  
  return (
    <mesh {...props} ref={ref}>
     < primitive object={scene} />
    </mesh>
  )
}

export default Sky_pano
