// /*
// Auto-generated by: https://github.com/pmndrs/gltfjsx
// Author: M_O (https://sketchfab.com/m_o)
// License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
// Source: https://sketchfab.com/3d-models/spacecraft-721cf3745abc47d8b4f58cfa7706cacb
// Title: Spacecraft
// */

// import { useRef,useEffect } from "react";
// import { useGLTF } from "@react-three/drei";
// import { useFrame,useThree } from "@react-three/fiber";
// import {a} from '@react-spring/three'

// import spacecraftScene from '../assets/3d/spacecraft.glb'

// const spacecraft = (props) => {
//   const group = useRef();
//   const { nodes, materials, scene,animations } = useGLTF(spacecraftScene);
//   return (
//     <a.group ref={group} {...props} >
//       <group name="Sketchfab_Scene">
//         <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
//           <group name="root">
//             <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
//               <group
//                 name="sh_3"
//                 position={[0, -0.102, 0]}
//                 scale={[0.463, 0.463, 0.346]}
//               >
//                 <mesh
//                   name="Object_4"
//                   castShadow
//                   receiveShadow
//                   geometry={nodes.Object_4.geometry}
//                   material={materials.Material}
//                 />
//                 <mesh
//                   name="Object_5"
//                   castShadow
//                   receiveShadow
//                   geometry={nodes.Object_5.geometry}
//                   material={materials["Glass.001"]}
//                 />
//                 <mesh
//                   name="Object_6"
//                   castShadow
//                   receiveShadow
//                   geometry={nodes.Object_6.geometry}
//                   material={materials["Outer.002"]}
//                 />
//                 <mesh
//                   name="Object_7"
//                   castShadow
//                   receiveShadow
//                   geometry={nodes.Object_7.geometry}
//                   material={materials["Light.002"]}
//                 />
//                 <mesh
//                   name="Object_8"
//                   castShadow
//                   receiveShadow
//                   geometry={nodes.Object_8.geometry}
//                   material={materials.panel}
//                 />
//                 <mesh
//                   name="Object_9"
//                   castShadow
//                   receiveShadow
//                   geometry={nodes.Object_9.geometry}
//                   material={materials["Material.004"]}
//                 />
//                 <mesh
//                   name="Object_10"
//                   castShadow
//                   receiveShadow
//                   geometry={nodes.Object_10.geometry}
//                   material={materials["Material.002"]}
//                 />
//                 <mesh
//                   name="Object_11"
//                   castShadow
//                   receiveShadow
//                   geometry={nodes.Object_11.geometry}
//                   material={materials["Light.001"]}
//                 />
//                 <mesh
//                   name="Object_12"
//                   castShadow
//                   receiveShadow
//                   geometry={nodes.Object_12.geometry}
//                   material={materials["Outer.001"]}
//                 />
//                 <mesh
//                   name="Object_13"
//                   castShadow
//                   receiveShadow
//                   geometry={nodes.Object_13.geometry}
//                   material={materials["Black.001"]}
//                 />
//               </group>
//             </group>
//           </group>
//         </group>
//       </group>
//     </a.group>
//   );
// }

// useGLTF.preload("/spacecraft.glb");

// export default spacecraft;

import { useRef, useEffect } from 'react';
import { useAnimations, useGLTF } from '@react-three/drei';

import SpacecraftScene from '../assets/3d/spacecraft.glb';

const Spacecraft = ({ isRotating, isScrolling, ...props }) => {
  const ref = useRef();
  const { scene, animations } = useGLTF(SpacecraftScene);
  const { actions } = useAnimations(animations, ref);

  useEffect(() => {
    const hoverAction = actions['Hover'];

    hoverAction.play();
    if (isRotating || isScrolling) {
      // Adjust speed by setting the duration (lower duration = faster)
      hoverAction.setDuration(2); // Adjust the duration as needed
    } else {
      hoverAction.setDuration(27);
    }
  }, [actions, isRotating, isScrolling]);

  return (
    <mesh {...props} ref={ref}>
      <primitive object={scene} />
    </mesh>
  );
};

export default Spacecraft;

